server {
  listen 28080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /home-prototype-1.html { return 404; }
  location = /home-prototype-3.html { return 404; }
  location = /home-prototype-4.html { return 404; }
  location = /home-prototype-5.html { return 404; }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /healthz {
    add_header Content-Type text/plain;
    return 200 'ok';
  }
}
